name: cPanel Automated Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4  

    - name: Set up Node.js Environment
      uses: actions/setup-node@v4  
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies & Build Next.js
      run: |
        npm install
        npm run build
      env:
        NEXT_PUBLIC_SANITY_PROJECT_ID: "33xgn627"
        NEXT_PUBLIC_SANITY_DATASET: "production"
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    - name: Deploy Production Files via rsync over SSH
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: "nursing1"  
        REMOTE_PORT: "2222" # Connects to cPanel's custom port
        TARGET: "/home3/nursing1/elpiswellness.co.ke/" 
        EXCLUDE: "/node_modules/, /.git/, /.github/, /src/"