name: cPanel Automated Deployment

on:
  push:
    branches:
      - main  # Triggers deployment when you push code to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4  

    - name: Set up Node.js Environment
      uses: actions/setup-node@v4  
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies & Build Next.js
      run: |
        npm install
        npm run build
      env:
        NEXT_PUBLIC_SANITY_PROJECT_ID: "33xgn627"
        NEXT_PUBLIC_SANITY_DATASET: "production"
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    - name: Sync Production Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  
        server-dir: /   
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          /src/**